vision:
  model_path: "best.onnx"
  conf_thresh: 0.4
  cam_id: 0

can:
  channel: "can0"
  bustype: "socketcan"
  id_start: 0x180
  id_end: 0x200
  send_delay: 0.5  # seconds
test_hours: 8
error_labels: ['Anti Lock Braking System',
    'Braking System Issue',
    'Charging System Issue',
    'Check Engine',
    'Electronic Stability Problem -ESP-',
    'Engine Overheating Warning Light',
    'Low Engine Oil Warning Light',
    'Low Tire Pressure Warning Light',
    'Master warning light',
    'SRS-Airbag']  # 需要监控的错误标签